// Generated by gencpp from file beginner_tutorials/TurtleWrite.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_TURTLEWRITE_H
#define BEGINNER_TUTORIALS_MESSAGE_TURTLEWRITE_H

#include <ros/service_traits.h>


#include <beginner_tutorials/TurtleWriteRequest.h>
#include <beginner_tutorials/TurtleWriteResponse.h>


namespace beginner_tutorials
{

struct TurtleWrite
{

typedef TurtleWriteRequest Request;
typedef TurtleWriteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TurtleWrite
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::TurtleWrite > {
  static const char* value()
  {
    return "d965374db2978a5042a2f36a27b7fe3f";
  }

  static const char* value(const ::beginner_tutorials::TurtleWrite&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::TurtleWrite > {
  static const char* value()
  {
    return "beginner_tutorials/TurtleWrite";
  }

  static const char* value(const ::beginner_tutorials::TurtleWrite&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::TurtleWriteRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::TurtleWrite >
template<>
struct MD5Sum< ::beginner_tutorials::TurtleWriteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::TurtleWrite >::value();
  }
  static const char* value(const ::beginner_tutorials::TurtleWriteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::TurtleWriteRequest> should match
// service_traits::DataType< ::beginner_tutorials::TurtleWrite >
template<>
struct DataType< ::beginner_tutorials::TurtleWriteRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::TurtleWrite >::value();
  }
  static const char* value(const ::beginner_tutorials::TurtleWriteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::TurtleWriteResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::TurtleWrite >
template<>
struct MD5Sum< ::beginner_tutorials::TurtleWriteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::TurtleWrite >::value();
  }
  static const char* value(const ::beginner_tutorials::TurtleWriteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::TurtleWriteResponse> should match
// service_traits::DataType< ::beginner_tutorials::TurtleWrite >
template<>
struct DataType< ::beginner_tutorials::TurtleWriteResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::TurtleWrite >::value();
  }
  static const char* value(const ::beginner_tutorials::TurtleWriteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_TURTLEWRITE_H
