// Generated by gencpp from file beginner_tutorials/TurtleWriteRequest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_TURTLEWRITEREQUEST_H
#define BEGINNER_TUTORIALS_MESSAGE_TURTLEWRITEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct TurtleWriteRequest_
{
  typedef TurtleWriteRequest_<ContainerAllocator> Type;

  TurtleWriteRequest_()
    : message()
    , scale(0.0)  {
    }
  TurtleWriteRequest_(const ContainerAllocator& _alloc)
    : message(_alloc)
    , scale(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef float _scale_type;
  _scale_type scale;





  typedef boost::shared_ptr< ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleWriteRequest_

typedef ::beginner_tutorials::TurtleWriteRequest_<std::allocator<void> > TurtleWriteRequest;

typedef boost::shared_ptr< ::beginner_tutorials::TurtleWriteRequest > TurtleWriteRequestPtr;
typedef boost::shared_ptr< ::beginner_tutorials::TurtleWriteRequest const> TurtleWriteRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message &&
    lhs.scale == rhs.scale;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d965374db2978a5042a2f36a27b7fe3f";
  }

  static const char* value(const ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd965374db2978a50ULL;
  static const uint64_t static_value2 = 0x42a2f36a27b7fe3fULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/TurtleWriteRequest";
  }

  static const char* value(const ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
"float32 scale\n"
;
  }

  static const char* value(const ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.scale);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleWriteRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::TurtleWriteRequest_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "scale: ";
    Printer<float>::stream(s, indent + "  ", v.scale);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_TURTLEWRITEREQUEST_H
